# directory: /mnt/comfy_data/output/webtoon/outsiders/prompts
# directory: /mnt/comfy_data/output/webtoon/This_Shithole_Company_is_Mine_Now/prompts
# directory: /mnt/comfy_data/output/webtoon/Teachers_Efforts/prompts
directory: /mnt/comfy_data/output/webtoon/Read_I_Became_a_Pornhwa_NPC/prompts
# output_file: /mnt/comfy_data/output/webtoon/outsiders/prompts/strings_count.yaml
# output_file: /mnt/comfy_data/output/webtoon/Teachers_Efforts/prompts/Teachers_Efforts_strings_count_all_001.yaml
output_file: ./Read_I_Became_a_Pornhwa_NPC_strings_count_all_001.yaml
scan_subdir: true
extensions:
  - txt