expression:
  - smile
  - angry
  - sad
  - blush
  - crying
  - ahegao
  - blush
  - bright_pupils
  - closed_eyes
  - closed_month
  - drooling
  - grin
  - one_eye_closed
  - saliva
  - sweat
  - sweatdrop
  - symbol-shaped_pupils
  - tongue_out
  - wavy_mouth
  - confused
  - closed_eyes
  - blank_eye
  - '@_@'
  - sanpaku
  - +_+
  - '>_<'
  - '>o<'
  - ^_^
person:
  - 1girl
  - 2girls
  - 3girls
  - 4girls
  - girls
  - boy
  - 1boy
  - 2boys
  - 3boys
  - 4boys
  - 6+boys
  - boys
  - man
  - woman
  - character
  - faceless
  - gyaru
  - hetero
  - solo
  - teeth
  - yuri
  - yaoi
  - husband_and_wife
  - angel
  - angel_and_devil
  - devil
style:
  - ahoge
  - heart_ahoge
  - hair
  - tail
  - hair_between_eyes
  - hair_
  - muscular
  - _eyes
  - black_eyes
  - aqua_eyes
  - black_eyes
  - green_eyes
  - brown_eyes
  - grey_eyes
  - red_eyes
  - parted_lips
  - ponytail
  - ribbon
  - thick_eyebrows
  - tatoo
  - bow
  - hair_ornament
  - hair_over_one_eye
  - single_hair_bun
  - hair_bun
  - eyewear
  - framed_eyewear
  - angel_wings
  - anger_vein
  - animal_ears
  - animal_hands
  - braid
  - braid_
  - braided_bun
  - braided_ponytail
  - braided_
  - condom_belt
  - condom_
  - cum_in_
  - cum_on_
  - dark_skin
bust_size:
  - large_breasts
  - medium_breasts
  - small_breasts
  - huge_breasts
body_parts:
  - anus
  - anus_
  - anus_peek
  - anal
  - ass
  - collarbone
  - pussy
  - vaginal
  - penis
  - lips
  - _body
  - mole
  - navel
  - nipple
  - pectorals
  - pussy_juice
  - stomach
  - testicles
  - thighs
  - teeth
  - tongue
  - abs  
  - penis
  - large_penis
  - sideboob
  - barefoot
action:
  - adjusting_
  - run
  - jump
  - walk
  - look
  - hold
  - holding
  - after
  - after_
  - ass_
  - grab
  - _grab
  - _lidding
  - press
  - sucking
  - sex
  - fellatio
  - cum
  - cumdrip
  - cunnilingus
  - deep_penetration
  - deepthroat
  - ejaculation
  - erection
  - fingering
  - french_kiss
  - grabbing
  - hand_on_another's_
  - hands_on_
  - holding
  - insert
  - fellatio
  - penetration
  - kiss
  - kissing
  - lactation
  - licking
  - licking_
  - lying
  - mating_press
  - oral
  - sitting
  - threesome
  - insertion
  - bouncing
  - job
  - spanking
  - sleeping
  - masturbation
  - cum_in_
  - cooperative_
  - paizuri
  - imminent_
  - nipple_tweak
  - drinking_
  - fingering_
  - grabbing_another's_
  - grabbing_
  - hand_on_another's_
  - hands_on_another's_
  - kissing_
  - looking_at_
accessary:
  - earrings
  - necklace
  - choker
  - condom
  - ear_piercing
  - earrings
  - jewelry
  - piercing
  - towel
  - vibrator
  - dildo
  - hairclip
  - iphone
  - phone
  - tablet
  - cake
  - cookie
  - chopsticks
  - dessert
outfit:
  - dress
  - jacket
  - uniform
  - skirt
  - bikini
  - bikini_bottom_only
  - bikini_top_only
  - bikini_under_clothes
  - bikini_
  - apron
  - outfit
  - backless
  - footwear
  - gloves
  - highleg
  - hood
  - hoodie
  - pants
  - bondage
  - clothed
  - nude
  - clothes_
  - completely_nude
  - denim
  - _lift
  - _pull
  - garter_belt
  - garter_straps
  - hat
  - latex
  - leotard
  - naked_towel
  - nipple_slip
  - nipple_tweak
  - nude
  - one_breast_out
  - open_
  - pajamas
  - sandals
  - shirt
  - shoes
  - short_shorts
  - short_sleeves
  - side-tie_
  - sidelocks
  - sleeveless
  - strapless
  - strapless_
  - swimsuit
  - thigh_boots
  - thighhighs
  - thong
  - topless
  - wedding_dress
  - sneakers
  - bondage
  - frills
  - off_shoulder
  - bowtie
  - cardigan
  - bare
  - bare_
  - red_dress
  - dress
  - camisole
  - white_camisole
  - _one-piece_swimsuit
  - black_one-piece_swimsuit
  - blue_one-piece_swimsuit
  - cameltoe
  - bowtie
  - bow
underwear:
  - underwear
  - bra
  - panties
  - shorts
  - pantyhose
position:
  - position
  - cowgirl
  - _on_top
posing:
  - all_fours
  - arm
  - arm_
  - bent
  - doggystyle
  - kneeling
  - leaning_forward
  - leg_
  - missionary
  - spread_legs
  - spread_pussy
  - standing
  - straddling
  - upright_straddle
  - hands_on_
  - cum_on_
  - seiza
  - wariza
  - arm_around_
  - arm_behind_
  - arm_
  - arms_around_
  - arms_behind_
  - arms_under_
  - arms_
  - between_breasts
  - between_legs
  - between_thighs
  - between_
  - covering_
  - finger_in_
  - finger_to_
  - hand_in_
  - hand_on_own_
  - hands_on_own_
  - holding
  - holding_another's_
  - implied_fellatio
  - implied_fingering
  - implied_
location:
  - room
  - street
  - school
  - forest
  - beach
  - bed
  - indoors
  - on_bed
  - couch
  - on_desk
  - outdoors
  - bathroom
  - counter
time:
  - night
  - morning
  - sunset
camera_angle:
  - low angle
  - high angle
  - close up
  - close-up
  - cowboy_shot
  - forcus
  - _focus
  - facing_viewer
  - from_
  - looking_
  - _focus
  - on_back
  - portrait
  - profile
  - solo_focus
  - undercut
  - upper_body
  - solo_focus
  # add
  - _angle
  - _shot
  - _view
  - telephoto
  - eye_level
  - three-quater_view
# viewpoint:
  - first person
  - third person
  - side view
  - pov
  - pov_crotch
  - female_pov
text:
  - text
  - chinese_text
  - french_text
  - engrish_text
  - italian_text
  - mixed-language_text
  - romaji_text
  - russian_text
  - simplified_chinese_text
  - spanish_text
  - thai_text
  - _text
  - roman_numeral
  - name
  - twitter_username
  - artist_name
kouka:
  - sound_effects
  - speech_bubble
  - motion_
  - spoken_
  - spoken_ellipsis
  - watermark
  - heart
  - speed_lines
  - '!'
  - '!!'
  - '!?'
  - '...'
  - '?'
  - 1koma
  - 2koma
  - 3koma
  - 4koma
  - comic
  - emphasis_lines
nsfw:
  - censored
  - uncensored
  - censored_nipples
  - censored_text
  - sfw
  - nsfw
  - convenient_censoring
  - mosaic_censoring
