expression:   # 表情
  - smile
  - angry
  - sad
  - blush
  - crying
  - ahegao
  - blush
  - bright_pupils
  - closed_eyes
  - closed_month
  - drooling
  - grin
  - one_eye_closed
  - saliva
  - sweat
  - sweatdrop
  - symbol-shaped_pupils
  - tongue_out
  - wavy_mouth
  - confused
  - closed_eyes
  - blank_eye
  - '@_@'
  - sanpaku
  - +_+
  - '>_<'
  - '>o<'
  - ^_^
character:    # キャラクター, 人物
  - 1girl
  - 2girls
  - 3girls
  - 4girls
  - girls
  - boy
  - 1boy
  - 2boys
  - 3boys
  - 4boys
  - 6+boys
  - boys
  - man
  - woman
  - character
  - faceless
  - gyaru
  - hetero
  - solo
  - yuri
  - yaoi
  - husband_and_wife
  - angel
  - angel_and_devil
  - devil
  - couple
  - threesome
  - ffm_threesome
  - fmm_threesome
  - _threesome
character_features:  # キャラクタ変換時に置換または削除候補となる
  - ahoge
  - heart_ahoge
  - hair
  - tail
  - hair_between_eyes
  - hair_
  - brown_hair
  - black_hair
  - white_hair
  - blonde_hair
  - grey_hair
  - pink_hair
  - blue_hair
  - _hair
  - _eyes
  - black_eyes
  - aqua_eyes
  - black_eyes
  - green_eyes
  - brown_eyes
  - grey_eyes
  - red_eyes
  - parted_lips
  - ponytail
  - ribbon
  - thick_eyebrows
  - tatoo
  - bow
  - hair_ornament
  - hair_over_one_eye
  - single_hair_bun
  - hair_bun
  - eyewear
  - framed_eyewear
  - angel_wings
  - anger_vein
  - animal_ears
  - dog_ears
  - cat_ears
  - rabbit_ears
  - animal_hands
  - braid
  - braid_
  - braided_bun
  - braided_ponytail
  - braided_
  - dark_skin
  - _writing
  - body_writing
  # male body attributes
  - muscular
  - muscular_male
  - abs
  - pectorals
  - breasts_apart
  - bara
  - bowl_cut
body_attributes:
  - anus
  - anus_
  - anus_peek
  - anal
  - ass
  - collarbone
  - pussy
  - vaginal
  - penis
  - lips
  - _body
  - mole
  - navel
  - nipple
  - pussy_juice
  - stomach
  - testicles
  - thighs
  - teeth
  - tongue
  - penis
  - large_penis
  - sideboob
  - barefoot
  - cum_in_
  - cum_on_
  - cum_on_breasts
  - covered_nipples
  - covering_breasts
  - mole_on_breast
  - arm_tattoo
  - shoulder_tattoo
  - tattoo
  - _tattoo
  - nape
  - sweat
  - sweatdrop
  - toenails
  - covered_navel
  - v-shaped_eyebrows
bust_size:  # キャラクタ変換時に置換または削除候補となる
  - large_breasts
  - medium_breasts
  - small_breasts
  - huge_breasts
  - alternate_breast_size
accessary:
  - earrings
  - necklace
  - choker
  - condom
  - ear_piercing
  - earrings
  - jewelry
  - piercing
  - towel
  - vibrator
  - dildo
  - hairclip
  - iphone
  - phone
  - tablet
  - cake
  - cookie
  - chopsticks
  - dessert
  - condom_belt
  - condom_
  - cup
  - sex_toy
  - monitor
  - holographic_monitor
  - tablet_pc
  - computer
  - clock
  - sunglasses
  - hat
outfit:  # キャラクタ変換時に置換または削除候補となる
  - dress
  - jacket
  - uniform
  - skirt
  - bikini
  - bikini_bottom_only
  - bikini_top_only
  - bikini_under_clothes
  - bikini_
  - apron
  - outfit
  - backless
  - footwear
  - gloves
  - highleg
  - hood
  - hoodie
  - pants
  - bondage
  - cardigan
  - clothed
  - nude
  - clothes_
  - completely_nude
  - denim
  - _lift
  - _pull
  - garter_belt
  - garter_straps
  - hat
  - latex
  - leotard
  - naked_towel
  - nipple_slip
  - nipple_tweak
  - nude
  - one_breast_out
  - open_
  - pajamas
  - sandals
  - shirt
  - _shoes
  - shorts
  - _shorts
  - short_shorts
  - denim_shorts
  - brown_shorts
  - grey_shorts
  - blue_shorts
  - short_sleeves
  - side-tie_
  - sidelocks
  - sleeveless
  - strapless
  - strapless_
  - swimsuit
  - thigh_boots
  - thighhighs
  - thong
  - topless
  - wedding_dress
  - sneakers
  - bondage
  - frills
  - off_shoulder
  - bowtie
  - cardigan
  - bare
  - bare_
  - red_dress
  - dress
  - camisole
  - white_camisole
  - _one-piece_swimsuit
  - black_one-piece_swimsuit
  - blue_one-piece_swimsuit
  - cameltoe
  - bowtie
  - bow
  - white_border
  - grey_border
  - floral_print
  - breast_pocket
  - tank_top
  - see-through
  - black_tank_top
  - green_cardigan
  - green_sweater
  - kimono
  - black_thighhighs
  - black_leotard
  - bra_pull
  - zettai_ryouiki
  - socks
  - jeans
  - loafers
  - socks
  - jeans
  - pajamas
  - blue_pajamas
  - _pajamas
  - bandeau
  - red_bandeau
  - white_bandeau
  - _bandeau
  - animal_print, 
  - butterfly_print
  - _print 
underwear:  # キャラクタ変換時に置換または削除候補となる
  - underwear
  - panties
  - grey_panties
  - black_panties
  - red_panties
  - blue_panties
  - white_panties
  - brown_panties
  - _panties
  - bra
  - print_bra
  - black_bra
  - grey_bra
  - purple_bra
  - blue_bra
  - lace_bra
  - _bra
  - pantyhose
  - black_pantyhose
  - fishnet_pantyhose
  - _pantyhose
  - fishnets
action:
  - adjusting_
  - run
  - jump
  - walk
  - look
  - hold
  - holding
  - after
  - after_
  - ass_
  - grab
  - _grab
  - _lidding
  - press
  - sucking
  - sex
  - fellatio
  - cum
  - cumdrip
  - cunnilingus
  - deep_penetration
  - deepthroat
  - ejaculation
  - erection
  - fingering
  - french_kiss
  - grabbing
  - hand_on_another's_
  - hands_on_
  - holding
  - insert
  - fellatio
  - penetration
  - kiss
  - kissing
  - lactation
  - licking
  - licking_
  - looking_at_
  - looking_at_penis
  - lying
  - mating_press
  - oral
  - sitting
  - threesome
  - insertion
  - bouncing
  - job
  - smelling
  - spanking
  - sleeping
  - masturbation
  - cum_in_
  - cooperative_
  - paizuri
  - imminent_
  - nipple_tweak
  - drinking_
  - fingering_
  - grabbing_another's_
  - grabbing_
  - hand_on_another's_
  - hands_on_another's_
  - kissing_
  - looking_at_
  - kabedon
  - breast_press
  - bouncing_breasts
  - grabbing_another's_breast
  - breasts_squeezed_together
  - face_to_breasts
  - looking_at_phone
  - showering
  - pulling_another's_clothes
posing:
  - all_fours
  - arm
  - arm_
  - bent
  - doggystyle
  - kneeling
  - leaning_forward
  - leg_
  - missionary
  - spread_legs
  - spread_pussy
  - spread_
  - standing
  - straddling
  - upright_straddle
  - hands_on_
  - cum_on_
  - seiza
  - wariza
  - arm_around_
  - arm_behind_
  - arm_
  - arms_around_
  - arms_behind_
  - arms_under_
  - arms_
  - between_breasts
  - between_legs
  - between_thighs
  - between_
  - covering_
  - finger_in_
  - finger_to_
  - hand_in_
  - hand_on_own_
  - hands_on_own_
  - holding
  - holding_another's_
  - implied_fellatio
  - implied_fingering
  - implied_
  - grabbing_own_breast
  - grabbing_own_
  - covering_face
  - covered_face
  - dogeza
  - seiza
  - spread_legs
  - erection
position:
  - position
  - cowgirl
  - _on_top
location:
  - room
  - street
  - school
  - forest
  - beach
  - bed
  - indoors
  - on_bed
  - couch
  - on_desk
  - outdoors
  - bathroom
  - counter
  - toilet
time:
  - night
  - morning
  - sunset
camera_angle:
  - low angle
  - high angle
  - close up
  - close-up
  - cowboy_shot
  - focus
  - _focus
  - facing_viewer
  - from_
  - looking_
  - _focus
  - on_back
  - portrait
  - profile
  - solo_focus
  - undercut
  - upper_body
  - solo_focus
  # add
  - _angle
  - _shot
# viewpoint:
  - first person
  - third person
  - side view
  - pov
  - pov_crotch
  - female_pov
  - three-quater_view
  - _view
  - telephoto
  - eye_level
text:
  - text
  - chinese_text
  - french_text
  - engrish_text
  - italian_text
  - mixed-language_text
  - romaji_text
  - russian_text
  - simplified_chinese_text
  - spanish_text
  - thai_text
  - _text
  - roman_numeral
  - name
  - twitter_username
  - artist_name
  - spoken_exclamation_mark
effect:
  - sound_effects
  - speech_bubble
  - motion_
  - spoken_
  - spoken_ellipsis
  - watermark
  - heart
  - speed_lines
  - '!'
  - '!!'
  - '!?'
  - '...'
  - '?'
  - 1koma
  - 2koma
  - 3koma
  - 4koma
  - comic
  - emphasis_lines
  - blurry
  - blurry_background
art_style:  # 画像の雰囲気を変更するときに差し替える
  - anime_style
  - sketch
  - monochrome
  - watercolor
  - _background
  - white_background
  - simple_background
  - gradient_background
  - floral_background
  - grey_background
  - black_background
  - pink_background
  - blue_background
  - brown_background
  - halftone_background
  - red_background
  - yellow_background
rating:
  - censored
  - uncensored
  - bar_censor
  - censored_nipples
  - censored_text
  - sfw
  - nsfw
  - convenient_censoring
  - mosaic_censoring
  - watermark
misc:
  - unknown
  - virtual_youtuber
  - goggles
  - android_
  # etc others
  - atago_\(kancolle\)
  - atago_\(stunning_speedster\)_\(azur_lane\), 
  - beidou_\(genshin_impact\)
  - emiya_shirou
  - houshou_\(kancolle\)
  - hu_tao_\(genshin_impact\)
  - jirai_kei
  - kitagawa_marin
  - kuroki_tomoko
  - kotomine_kirei
  - komi_shouko
  - mori_calliope
  - natsuiro_matsuri
  - otoko_no_ko
  - oozora_subaru
  - roman_numeral
  - sendai_hakurei_no_miko
  - shirase_sakuya
  - suzuhara_lulu
  - todoroki_shouto
  - uesugi_fuutarou
  - watson_amelia
  - yaoyorozu_momo
  - yorha_no._2_type_b
  # misc
  